version: "3.3"

services:
  web:
    build: .
    restart: always
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - ./storage:/app/storage
    links:
      - db
      - redis
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      REDIS_URL: ${REDIS_URL}
      RAILS_ENV: ${ENV}
      RAILS_SERVE_STATIC_FILES: 'true'
      RAILS_LOG_TO_STDOUT: 'true'

  db:
    image: mysql:8
    command: [--default-authentication-plugin=mysql_native_password]
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}

  redis:
    image: library/redis:alpine