version: "3.3"

services:
  web:
    build: .
    entrypoint: /app/docker-entrypoint.sh
    command: ["rails", "server", "-b", "0.0.0.0"]
    restart: always
    ports:
      - "3000:3000"
      - "4000:4000"
    tty: true
    volumes:
      - .:/app
    links:
      - db
      - redis
      - smtp
      - webpacker
    env_file:
      - .env/development/web
      - .env/development/database
      - .env/development/redis
      - .env/development/smtp

  sidekiq:
    depends_on:
      - db
      - redis
      - smtp
    build: .
    command: sidekiq
    volumes:
      - '.:/app'
    env_file:
      - .env/development/web
      - .env/development/database
      - .env/development/redis
      - .env/development/smtp

  webpacker:
    build: .
    command: ./bin/webpack-dev-server
    ports:
      - "3035:3035"
    volumes:
      - .:/app
    env_file:
      - .env/development/web
      - .env/development/database

  selenium_chrome:
    image: selenium/standalone-chrome-debug
    ports:
    - "5901:5900"

  db:
    image: mysql:8
    command: [--default-authentication-plugin=mysql_native_password]
    restart: always
    ports:
      - "13306:3306"
    volumes:
    - db_data:/var/lib/mysql
    env_file:
      - .env/development/database

  redis:
    image: library/redis:alpine
  
  smtp:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  db_data:
