version: "3.3"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    tty: true
    links:
      - db
      - redis
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: instagram_production
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: 'true'
      RAILS_LOG_TO_STDOUT: 'true'
      REDIS_URL: redis://redis:6379/0

  db:
    image: mysql:8
    command: [--default-authentication-plugin=mysql_native_password]
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root

  redis:
    image: library/redis:alpine